name: Build Only (No Publish)

on:
  workflow_dispatch:
 
jobs:
  run-tests:
    uses: SilverPineSoftware/UUKotlinBuild/.github/workflows/uu_build.yml@main
    with:
      module_name: 'library'
      